spring:
  application:
    name: mafia-master-bot
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      javax:
        persistence:
          validation:
            mode: none
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    host: localhost
    port: 5432
    database: ${spring.application.name}
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/migration/changelog.xml

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
  files:
    static:
      rules:
        path: "classpath:static/rules.pdf"
        alternative-web-path: "https://www.mafiavip.ru/game_rules"

mafia:
  address:
    physical: "Северная 302, 2 этаж"
    yandex-map-link: "https://yandex.ru/maps/org/mafiya_vip/198395698457"